title: Curb Signs
description: Custom curb signs for birthdays, events, and celebrations in the Greater Toronto Area.
baseurl: "/curb_signs_website"
url: "https://designer-ops.github.io"

# Build settings
markdown: kramdown
theme: null
plugins: []

# Exclude build artifacts
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor
  - README.md
