title: Curb Signs Inc.
description: Expert custom signage manufacturer in Toronto. Billboards, channel letters, wayfinding solutions & interior displays. Full-service design and installation.
baseurl: ""
url: "https://curbsigns.ca"
repository: designer-ops/curb_signs_website

# Build settings
markdown: kramdown
theme: null
plugins:
  - jekyll-sitemap
  - jekyll-seo-tag
  - jekyll-feed

# Exclude build artifacts
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor
  - README.md

# SEO Settings
author:
  name: Curb Signs Inc.
  email: info@curbsigns.ca
  
twitter:
  username: curbsignsinc

og_image: /assets/images/curb-signsing-white.png